### ISSUE TITLE
When using multiple `compiles` in a single test, ONLY the last one determines the tests outcome.

### ISSUE THREAD

**Issue by fischerscode** [rrousselGit/expect_error#8]
**Describe the bug**
Maybe this is totally obvious and I'm the problem, when using multiple `compiles` in a single test, ONLY the last one determines the tests outcome.

**To Reproduce**
This example succeeds but it shouldn't.
```dart
import 'package:expect_error/expect_error.dart';
import 'package:test/test.dart';

void main() async {
  final library = await Library.parseFromStacktrace();
  test('...', () async {
    await expectLater(library.withCode('NoSuchClass? test;'), compiles);
    await expectLater(library.withCode(''), compiles);
  });
}
```

**Expected behavior**
It should fail due to `NoSuchClass` being a `UNDEFINED_CLASS`. (It does, when swapping the two expects.)

**Workaround**
Just split them into multiple tests, like I finally did [here](https://github.com/serverpod/serverpod/pull/625/commits/fdb984f1095556f1b9050dd91baa4c1b479aa9e0).

**Comment by rrousselGit** [comment]
That's a funny bug.
I'll admit I'm a bit busy right now. Fancy looking into it?

**Comment by fischerscode** [comment]
I will, within the next days. But I can't promise anything.

**Comment by fischerscode** [comment]
@rrousselGit #9 seems to fix the behavior.
